catalog:
  db:
    endpoint: "bedrock-mysql.cob0620wqmoq.us-east-1.rds.amazonaws.com:3306"
    name: retail
    existingSecret: retail-mysql-secret
    secretKey: password

orders:
  db:
    endpoint: "bedrock-postgres.cob0620wqmoq.us-east-1.rds.amazonaws.com:5432"
    name: retail_pg
    existingSecret: retail-postgres-secret
    secretKey: password

carts:
  dynamodb:
    tableName: bedrock-retail-carts
    awsRegion: us-east-1
    createTable: false

activemq:
  enabled: true

ui:
  service:
    type: ClusterIP
